### ISSUE TITLE
logs/graphs/reports

### ISSUE THREAD

**Issue by clawmvp** [Bandic007/WebVirtCloud-B7#2]
hello, can https://grafana.com/ be integrated into virtcloud?

**Comment by Bandic007** [comment]
I will have to check this with the original developer - it is an interesting question. WebVirtCloud is writing its stuff in SQLite3 database, so I guess if Grafana can read from there it can.

**Comment by clawmvp** [comment]
it will be a nice feature, i don t have the necessary skills to do it myself.

**Comment by Bandic007** [comment]
I am now working on implementing WebVirtCloud to work by default with PostgreSQL database instead of sqlite3. When this is achieved, adding the PostgreSQL database as a source in grafana is supported by default so it can be monitored.
Another story that I need to check here is also what information is being recorded in this sqlite3/postgresql dabatase which webvirtcloud is going to use, in order to know what can be monitored by grafana and what not.
